language: node_js
node_js:
   - "0.8"
services:
   - mongodb
before_install:
   - npm install -g bower
   - npm install -g grunt-cli
   - cd alex-web/ && bower install
   - cd ../alex-chrome/ && bower install && cd ..

