language: node_js
node_js:
   - "0.8"
services:
   - mongodb
before_install:
   - npm install -g bower
   - cd alex-web/ && npm install grunt-cli && bower install
   - cd ../alex-chrome/ && npm install grunt-cli && bower install && cd ..
script:
   - npm run-script alex-web
   - npm run-script alex-chrome