language: node_js
node_js:
   - "0.10"
services:
   - mongodb
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - cd alex-web/ && npm install && bower install
  - cd ../alex-chrome/ && npm install && bower install && cd ..
script:
   - npm run-script alex-web
   - npm run-script alex-chrome